apiVersion: v1
kind: Service
metadata:
  name: employee-management-system-service
spec:
  selector:
    app: employee-management-system
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer