apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-management-system
  template:
    metadata:
      labels:
        app: employee-management-system
    spec:
      containers:
        - name: employee-management-system
          # image: employee-management-system:1.0.0 # For Minikube
          image: gcr.io/proverbial-keel-439502-u6/employee-management-system:1.0.0 # For GKE
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets